### ISSUE TITLE
Feature Request: Free Text Content type or plain XML

### ISSUE THREAD

**Issue by pdemro** [ddesch/SP-REST-JSON#1]
Add the ability to request plain XML as a part of this extension (rather than ATOM/XML).  This would allow FireFox out-of-box XML viewer to work with the SP Rest API

**Comment by ddesch** [comment]
Hi Phillip,

I'll try to add it to the next version which should be released in the next 2 weeks.

Regards

Daniel

**Comment by ddesch** [comment]
Done and published in version 1.2.1:
Firefox: https://addons.mozilla.org/de/firefox/addon/sp-rest-json/
Chrome: https://chrome.google.com/webstore/detail/sp-rest-json/kcdolhjbipnfgefpjaopfbjbannphidh
