### ISSUE TITLE
Dark theme and Firefox

### ISSUE THREAD

**Issue by kandiesky** [ddesch/SP-REST-JSON#10]
Heyo there!

Since the 1.5.0 update this extension has a very weird interaction with Firefox (v. 105). When you have dark theme enabled, sites will load the extension's stylesheet.
![image](https://user-images.githubusercontent.com/22504305/186498075-354395b8-0680-432b-8555-7b8b9a8a8bad.png)

Eg:
![image](https://user-images.githubusercontent.com/22504305/186497458-06b8ee7b-39df-4f57-ad10-62b3939be00f.png)

Having the extension enabled in Firefox is all you need to reproduce this. I did not test on Chrome/Edge.

**Comment by ddesch** [comment]
Hi,

Yes, I've just reproduced it in Firefox 104.0 :(
I'll have a look.

**Comment by ddesch** [comment]
Should be solved with version 1.5.1
https://addons.mozilla.org/de/firefox/addon/sp-rest-json/
