### ISSUE TITLE
BUG: not working in the latest Firefox Developer Edition

### ISSUE THREAD

**Issue by Jwaegebaert** [ddesch/SP-REST-JSON#13]
In the latest version of Firefox Developer Edition (128.0b7), the `SP REST JSON` extension no longer works. Previously, it transformed API queries to JSON output directly in the browser. Now, when I test simple API queries like `_api/web` or `_api/web/Lists/GetByTitle('Site Pages')/items`, the extension fails and instead downloads the XML output. This used to work fine in older versions, but something has broken with this, or a previous, update.

**Comment by milanholemans** [comment]
I'm experiencing the same issue. Currently, the extension works in the normal Firefox client, but not in Firefox Developer Edition (which is several versions ahead).

**Comment by ddesch** [comment]
Thanks. I'll have a look.

**Comment by ddesch** [comment]
Hi,

I've just installed Firefox Developer Edition (128.0b8) and the SP REST JSON Addin. I'm not able to reproduce the issue.

Tested with:
OS: Windows 10 Pro Version 22H2
Test URL: https://www.icao.int/_api/web/
Setting for Accept header: application/json;odata=verbose

![grafik](https://github.com/ddesch/SP-REST-JSON/assets/11195439/84f61874-047c-4cba-bd33-f7e31544a5cc)

Could you please test with the same URL?

**Comment by milanholemans** [comment]
Hi @ddesch, thank you for looking into it so quick.

Just did some more tests. Seems like it's not working when the multi container extension is enabled in firefox developer edition: https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers. It does seems to work in the regular firefox version.
When I disable the container add-in, it's working again.
Strangely enough, it seems like this is only happening for SharePoint sites. Using your URL, it works, using a SharePoint REST API (https://tenant.sharepoint.com/sites/Playground/_api/Web/Lists), it fails.

So to reproduce it, I guess, you'll have to:

- Enable multi container add-in (https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers)
- Perform a SharePoint REST API query.

It's been working perfectly for years, until 2 weeks ago or something I started noticing this issue.

**Comment by ddesch** [comment]
Hi @milanholemans and @Jwaegebaert,

Now I was able to reproduce it with a REST API link to a SharePoint Online tenant.
I'll need to take a closer look but that'll take some time.

**Comment by milanholemans** [comment]
Take your time, your help is appreciated. This extension is too valuable 😊

**Comment by ddesch** [comment]
Hi @milanholemans and @Jwaegebaert,

I've updated the extension to version 1.6.0 in FireFox.
Please try to force an update / new installation.

**Comment by milanholemans** [comment]
At first sight, it seems to be working indeed! Many thanks @ddesch! Much appreciated!

**Comment by Jwaegebaert** [comment]
Awesome, thanks so much @ddesch!
