### ISSUE TITLE
Option to increase font size

### ISSUE THREAD

**Issue by joshtransient** [ddesch/SP-REST-JSON#2]
Hi there, this extension is amazing. However, I find the font size too small at 11px, and increasing the display scale in the browser always changes the size in tabs where I'm using the UI. Any way to offer an option to increase font-size for old fogeys like me that need glasses with lenses thicker than bulletproof windows? 🤓

**Comment by ddesch** [comment]
Hey Josh,

Thanks and good point. Which browser are you using?

Regards

Daniel

**Comment by joshtransient** [comment]
I’m on Edge (Chromium), beta 88.0.705.41. Appreciate the consideration!

**Comment by ddesch** [comment]
Hey Josh,

I'll have a look.

Regards

Daniel

**Comment by ddesch** [comment]
Hey Josh,

I've published a new version (1.4.0) for Firefox, Chrome and Edge.
The Firefox one is already available but for Chrome and Edge the review is still pending.

Regards

Daniel

**Comment by ddesch** [comment]
Chrome web store has finished the review ✔️
So only waiting for the review from Microsoft Edge-Add-Ons...

**Comment by joshtransient** [comment]
It is perfect, my dude. Thanks for the quick turnaround!
